-- MySQL Script generated by MySQL Workbench
-- Thu Aug 30 16:32:40 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rol` (
  `idRol` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL COMMENT 'Llave primaria de la tabla usuario',
  `email` VARCHAR(45) NOT NULL COMMENT 'correo electronico para identificacion del login',
  `password` VARCHAR(45) NOT NULL COMMENT 'contraseña para ingresar al login',
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `cedula` INT NULL,
  `rif` INT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `Rol_idRol` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Rol1_idx` (`Rol_idRol` ASC),
  CONSTRAINT `fk_Usuario_Rol1`
    FOREIGN KEY (`Rol_idRol`)
    REFERENCES `mydb`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Servicios` (
  `idServicios` INT NOT NULL,
  `fechaIncio` DATE NULL,
  `total` DECIMAL(8,2) NULL,
  `fechaCorte` DATE NULL COMMENT 'Fecha en la que se cobra el plan nuevamente ',
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idServicios`),
  INDEX `fk_Servicios_Usuario_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Servicios_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoPlan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoPlan` (
  `idTipoPlan` INT NOT NULL,
  `descripcion` VARCHAR(50) NOT NULL,
  `costoUnitario` DECIMAL(8,2) NULL,
  PRIMARY KEY (`idTipoPlan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Planes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Planes` (
  `idPlanes` INT NOT NULL,
  `precio` DECIMAL(8,2) NULL,
  `costo` DECIMAL(8,2) NULL,
  `Servicios_idServicios` INT NOT NULL,
  `TipoPlan_idTipoPlan` INT NOT NULL,
  PRIMARY KEY (`idPlanes`),
  INDEX `fk_Planes_Servicios1_idx` (`Servicios_idServicios` ASC),
  INDEX `fk_Planes_TipoPlan1_idx` (`TipoPlan_idTipoPlan` ASC),
  CONSTRAINT `fk_Planes_Servicios1`
    FOREIGN KEY (`Servicios_idServicios`)
    REFERENCES `mydb`.`Servicios` (`idServicios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Planes_TipoPlan1`
    FOREIGN KEY (`TipoPlan_idTipoPlan`)
    REFERENCES `mydb`.`TipoPlan` (`idTipoPlan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Canales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Canales` (
  `idCanales` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `horarioDia` VARCHAR(45) NOT NULL,
  `horarioHora` VARCHAR(45) NOT NULL,
  `precio` DECIMAL(8,2) NULL,
  PRIMARY KEY (`idCanales`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PlanCanales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PlanCanales` (
  `idPlanCanales` INT NOT NULL,
  `Canales_idCanales` INT NOT NULL,
  `Planes_idPlanes` INT NOT NULL,
  PRIMARY KEY (`idPlanCanales`, `Planes_idPlanes`),
  INDEX `fk_PlanCanales_Canales1_idx` (`Canales_idCanales` ASC),
  INDEX `fk_PlanCanales_Planes1_idx` (`Planes_idPlanes` ASC),
  CONSTRAINT `fk_PlanCanales_Canales1`
    FOREIGN KEY (`Canales_idCanales`)
    REFERENCES `mydb`.`Canales` (`idCanales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PlanCanales_Planes1`
    FOREIGN KEY (`Planes_idPlanes`)
    REFERENCES `mydb`.`Planes` (`idPlanes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
